export const REQUEST_TRANSFER = 'REQUEST_TRANSFER';
export const GET_TRANSFERS     = 'GET_TRANSFERS';
export const APPROVE_TRANSFER = 'APPROVE_TRANSFER';
export const REFUND_TRANSFER = 'REFUND_TRANSFER';